simulation_end_time_ns=7200000000000
dynamic_state_update_interval_ns=60000000000
isl_utilization_tracking_interval_ns=60000000000
isl_data_rate_megabit_per_s=10.0
gsl_data_rate_megabit_per_s=10.0
isl_max_queue_size_pkts=100
gsl_max_queue_size_pkts=100
enable_isl_utilization_tracking=true
simulation_seed=654148
satellite_network_dir=satellite_network_state
satellite_network_routes_dir=dynamic_state_60000ms_for_7200s
enable_tcp_flow_scheduler=true
tcp_flow_schedule_filename=tcp_flow_schedule.csv
tcp_flow_enable_logging_for_tcp_flow_ids=set(0,1,2,3,4)
enable_udp_burst_scheduler=true
udp_burst_schedule_filename=udp_burst_schedule.csv
udp_burst_enable_logging_for_udp_burst_ids=set(0,1,2,3,4)
enable_pingmesh_scheduler=true
pingmesh_interval_ns=5000000000
pingmesh_endpoint_pairs=set(625->626,626->627,627->628,628->629,629->630,630->631,631->632,632->633,633->634,634->635,635->636,636->637,637->638,638->639,639->640,640->641,641->642,642->643,643->644,644->645,645->646,646->647,647->648,648->649,649->650)
tcp_socket_type=TcpNewReno
